FROM node:20-bullseye
WORKDIR /app

ENV npm_config_optional=true

COPY package*.json angular.json tsconfig*.json ./
RUN npm install --legacy-peer-deps --include=optional
RUN npm install -g @angular/cli@20.3.6

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
